import { defineConfig } from 'vitepress'
import { studioScreenshotPlugin } from './markdown/studioScreenshot'

export default defineConfig({
  title: 'LLW',
  description: 'Lightweight LWJGL Wrapper — 2D render, audio, and math for Java',
  base: '/',
  outline: [2, 3],
  markdown: {
    theme: { light: 'github-light', dark: 'github-dark' },
    config(md) {
      studioScreenshotPlugin(md)
    },
  },
  themeConfig: {
    logo: '/llw-studio-logo.png',
    nav: [
      { text: 'Tutorials', link: '/tutorials/01-window' },
      { text: 'Studio', link: '/studio/' },
      { text: 'Guide', link: '/guide/getting-started' },
      { text: 'Render', link: '/render/overview' },
      { text: 'Audio', link: '/audio/overview' },
      { text: 'Math', link: '/math/overview' },
      { text: 'Cookbook', link: '/cookbook/mouse-picking' },
      { text: 'API', link: '/api/javadoc' },
    ],
    search: { provider: 'local' },
    sidebar: [
      {
        text: 'Introduction',
        items: [{ text: 'Home', link: '/' }],
      },
      {
        text: 'Architecture',
        collapsed: true,
        items: [
          { text: 'Engine Overview', link: '/architecture/engine-overview' },
          { text: 'Render Pipeline Deep Dive', link: '/architecture/render-pipeline' },
        ],
      },
      {
        text: 'Tutorials',
        collapsed: false,
        items: [
          { text: '1 — Your First Window', link: '/tutorials/01-window' },
          { text: '2 — Events & Input', link: '/tutorials/02-events' },
          { text: '3 — Textures', link: '/tutorials/03-textures' },
          { text: '4 — Sprites', link: '/tutorials/04-sprites' },
          { text: '5 — Shapes', link: '/tutorials/05-shapes' },
          { text: '6 — Text', link: '/tutorials/06-text' },
          { text: '7 — Transforms', link: '/tutorials/07-transforms' },
          { text: '8 — Camera & Views', link: '/tutorials/08-camera' },
          { text: '9 — Audio', link: '/tutorials/09-audio' },
          { text: '10 — Game Loop', link: '/tutorials/10-game-loop' },
        ],
      },
      {
        text: 'Guide',
        items: [
          { text: 'Getting Started', link: '/guide/getting-started' },
          { text: 'Project Setup', link: '/guide/project-setup' },
          { text: 'Coordinates & Frame Loop', link: '/guide/coordinates' },
        ],
      },
      {
        text: 'Render',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/render/overview' },
          { text: 'Window', link: '/render/window' },
          { text: 'Window Settings', link: '/render/window-settings' },
          { text: 'Events', link: '/render/events' },
          { text: 'Input', link: '/render/input' },
          { text: 'Graphics Context', link: '/render/graphics-context' },
          { text: 'Render Target', link: '/render/render-target' },
          { text: 'Color', link: '/render/color' },
          { text: 'Clock', link: '/render/clock' },
          { text: 'Textures', link: '/render/textures' },
          { text: 'Sprite', link: '/render/sprite' },
          { text: 'Rectangle', link: '/render/rectangle' },
          { text: 'Circle', link: '/render/circle' },
          { text: 'Renderables (hub)', link: '/render/renderables' },
          { text: 'Vertex Geometry', link: '/render/vertex-geometry' },
          { text: 'Draw State & Layers', link: '/render/draw-state' },
          { text: 'Transformable', link: '/render/transformable' },
          { text: 'Camera', link: '/render/camera' },
          { text: 'Text & Fonts', link: '/render/text-and-fonts' },
          { text: 'Offscreen', link: '/render/offscreen' },
          { text: 'Shaders', link: '/render/shaders' },
          { text: 'Resource Loading', link: '/render/resource-loading' },
        ],
      },
      {
        text: 'Audio',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/audio/overview' },
          { text: 'Audio Context', link: '/audio/audio-context' },
          { text: 'Sounds', link: '/audio/sounds' },
          { text: 'Sound Buffer', link: '/audio/sound-buffer' },
          { text: 'Music', link: '/audio/music' },
          { text: 'Playback', link: '/audio/playback' },
          { text: 'Listener', link: '/audio/listener' },
          { text: 'Formats & Loading', link: '/audio/formats' },
          { text: 'Resources', link: '/audio/resources' },
        ],
      },
      {
        text: 'Math',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/math/overview' },
          { text: 'Vectors', link: '/math/vectors' },
          { text: 'Matrix', link: '/math/matrix' },
          { text: 'Transforms', link: '/math/transforms' },
          { text: 'Rect', link: '/math/rect' },
          { text: 'Circle', link: '/math/circle' },
          { text: 'Line & Ray', link: '/math/line-ray' },
          { text: 'AABB', link: '/math/aabb' },
          { text: 'Geometry (hub)', link: '/math/geometry' },
          { text: 'Collision', link: '/math/collision' },
          { text: 'Interpolation', link: '/math/interpolation' },
          { text: 'Easing', link: '/math/easing' },
          { text: 'Splines & Noise', link: '/math/splines-noise' },
        ],
      },
      {
        text: 'Resources',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/resources/overview' },
          { text: 'Resource Manager', link: '/resources/resource-manager' },
          { text: 'Asset Lifecycle', link: '/resources/asset-lifecycle' },
          { text: 'Asset Packs', link: '/resources/asset-packs' },
          { text: 'Directory Scan', link: '/resources/directory-scan' },
        ],
      },
      {
        text: 'Cookbook',
        collapsed: true,
        items: [
          { text: 'Mouse Picking', link: '/cookbook/mouse-picking' },
          { text: 'Drag Sprite', link: '/cookbook/drag-sprite' },
          { text: 'Scroll Zoom Camera', link: '/cookbook/scroll-zoom-camera' },
          { text: 'Draw Order Layers', link: '/cookbook/draw-order-layers' },
          { text: 'Sprite Sheet', link: '/cookbook/sprite-sheet' },
          { text: 'Tinted Sprites', link: '/cookbook/tinted-sprites' },
          { text: 'Offscreen Minimap', link: '/cookbook/offscreen-minimap' },
          { text: 'Custom Renderable', link: '/cookbook/custom-renderable' },
          { text: 'Fixed Timestep', link: '/cookbook/fixed-timestep' },
          { text: 'Entity Lite', link: '/cookbook/entity-component-lite' },
          { text: 'Scene Stack', link: '/cookbook/scene-stack' },
          { text: 'Sound Pool', link: '/cookbook/sound-pool' },
          { text: 'Resource Manager', link: '/cookbook/resource-manager' },
          { text: 'Crossfade Music', link: '/cookbook/crossfade-music' },
          { text: 'Click Triangle', link: '/cookbook/click-triangle' },
          { text: 'Platformer AABB', link: '/cookbook/platformer-aabb' },
          { text: 'Tween UI', link: '/cookbook/tween-ui' },
          { text: 'Procedural Shake', link: '/cookbook/procedural-shake' },
        ],
      },
      {
        text: 'Best Practices',
        collapsed: true,
        items: [
          { text: 'Resource Lifecycle', link: '/best-practices/resource-lifecycle' },
          { text: 'Frame Loop', link: '/best-practices/frame-loop' },
          { text: 'Coordinates', link: '/best-practices/coordinates' },
          { text: 'Performance', link: '/best-practices/performance' },
          { text: 'Error Handling', link: '/best-practices/error-handling' },
          { text: 'IDE & Natives', link: '/best-practices/ide-and-natives' },
        ],
      },
      {
        text: 'Studio',
        collapsed: false,
        items: [
          {
            text: 'Introduction',
            collapsed: false,
            items: [
              { text: 'Overview', link: '/studio/' },
              { text: 'Getting started', link: '/studio/getting-started' },
              { text: 'Quickstart tutorial', link: '/studio/quickstart-tutorial' },
            ],
          },
          {
            text: 'Editor',
            collapsed: true,
            items: [
              { text: 'Editor shell', link: '/studio/editor-shell' },
              { text: 'Hierarchy', link: '/studio/hierarchy' },
              { text: 'Inspector', link: '/studio/inspector' },
              { text: 'Scene view', link: '/studio/scene-view' },
              { text: 'Game view', link: '/studio/game-view' },
              { text: 'Project and assets', link: '/studio/project-and-assets' },
              { text: 'Console', link: '/studio/console' },
              { text: 'UI theme and widgets', link: '/studio/ui-theme-and-widgets' },
              { text: 'Keyboard shortcuts', link: '/studio/keyboard-shortcuts' },
              { text: 'Undo and commands', link: '/studio/undo-and-commands' },
            ],
          },
          {
            text: 'Authoring',
            collapsed: true,
            items: [
              { text: 'Prefabs', link: '/studio/prefabs' },
              { text: 'Animation', link: '/studio/animation' },
              { text: 'Tilemaps', link: '/studio/tilemaps' },
              { text: 'Tilesets and rule tiles', link: '/studio/tilesets-and-rule-tiles' },
              { text: 'Tile palette', link: '/studio/tile-palette' },
              { text: 'Physics 2D', link: '/studio/physics-2d' },
              { text: 'In-game UI', link: '/studio/in-game-ui' },
            ],
          },
          {
            text: 'Runtime',
            collapsed: true,
            items: [
              { text: 'Play mode', link: '/studio/play-mode' },
              { text: 'Scripting', link: '/studio/scripting' },
              { text: 'Scripting cookbook', link: '/studio/scripting-cookbook' },
              { text: 'ECS and GameObjects', link: '/studio/ecs-and-gameobjects' },
              { text: 'Scenes and serialization', link: '/studio/scenes-and-serialization' },
              { text: 'Systems reference', link: '/studio/systems-reference' },
              { text: 'llw engine integration', link: '/studio/llw-engine-integration' },
              { text: 'Memory and performance', link: '/studio/memory-and-performance' },
            ],
          },
          {
            text: 'Scripting API',
            collapsed: true,
            items: [
              { text: 'Overview', link: '/studio/scripting-api/overview' },
              { text: 'Scene and entities', link: '/studio/scripting-api/scene-and-entities' },
              { text: 'Components', link: '/studio/scripting-api/components' },
              { text: 'Physics', link: '/studio/scripting-api/physics' },
              { text: 'Animation', link: '/studio/scripting-api/animation' },
              { text: 'UI', link: '/studio/scripting-api/ui' },
              { text: 'Input and keys', link: '/studio/scripting-api/input-and-keys' },
            ],
          },
          {
            text: 'Reference',
            collapsed: true,
            items: [
              { text: 'Components reference', link: '/studio/components-reference' },
              { text: 'Project format', link: '/studio/project-format' },
              { text: 'Troubleshooting', link: '/studio/troubleshooting' },
              { text: 'Build and export', link: '/studio/build-and-export' },
            ],
          },
        ],
      },
      {
        text: 'More',
        items: [
          { text: 'FAQ', link: '/faq' },
          { text: 'SFML Migration', link: '/sfml-migration' },
        ],
      },
      {
        text: 'Examples',
        collapsed: true,
        items: [
          { text: 'Minimal Window', link: '/examples/minimal-window' },
          { text: 'Sprites & Shapes', link: '/examples/sprites-and-shapes' },
          { text: 'Audio Demo', link: '/examples/audio-demo' },
          { text: 'Full Demo', link: '/examples/full-demo' },
        ],
      },
      {
        text: 'API Reference',
        items: [{ text: 'Javadoc', link: '/api/javadoc' }],
      },
    ],
    socialLinks: [],
    footer: {
      message: 'LLW — Lightweight LWJGL Wrapper',
      copyright: 'Copyright © 2026',
    },
    docFooter: { prev: 'Previous', next: 'Next' },
  },
})
